name: achievement_tracker
description: Just another Achievement Tracker...

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  logging: ^1.0.2

  # Сервисы Firebase
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0

  # Для сериализации объектов из/в JSON
  json_annotation: ^4.3.0

  hive: ^2.0.6
  flutter_riverpod: ^1.0.3
  beamer: ^1.4.0
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  ross_lints:
    git:
      url: git://github.com/RossHS/ross_lint_ruleset

  # Генерация кода запаковки и распаковки объектов в json
  json_serializable: ^6.0.0
  build_runner: ^2.0.6

  # Mock зависимость firestore для тестирования кода
  fake_cloud_firestore: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
